version: '3'
services:
  db:
    image: postgres
    environment: 
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: postgres
      POSTGRES_DB: tasks
    volumes: 
      - ./pgdata:/var/lib/postgresql/data
    ports: 
      - '5432:5432'