version: '3'
services:
  db:
    image: postgres:11.4-alpine
    container_name: postgres
    ports:
      - 5432:5432
    volumes:
      - ./pg_data:/var/lib/postgresql/data/pgdata
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: tasks
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: always
  app:
    command: npm start